# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$Ka0NZGZK$3161565c2e46e1ceb82e5531848c2b8dc7dfe9a8'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'sqlite:///simple.db'
GITHUB_USERNAME = ''
CONTACT_EMAIL = ''
BLOG_TITLE = ''
BLOG_TAGLINE = ''
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'AATC3KXGZETU3RQMVHFZ37XUUF5EGQRBSGHSSAZXO3T5RTH2UNSQ===='
DISQUS_SHORTNAME = ''
USE_ADDTOANY = True
USE_SUBTOME = False
