# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$6eTY0JyZ$498d480dc107d7e05d1a7de982edba1c5b52c06f'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'sqlite:///simple.db'
GITHUB_USERNAME = 'gerbal'
CONTACT_EMAIL = ''
BLOG_TITLE = 'Test Simple Deployment'
BLOG_TAGLINE = 'Help! I\'m trapped in a testing instance'
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'ATJTFWHLQK7YCPJCFUMLOAQGMUAUUOYQBCOHBBUCYMCJMUB3AR2Q===='
DISQUS_SHORTNAME = ''
USE_ADDTOANY = True
USE_SUBTOME = False
