# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$e88qroyy$2b99993b426e206b1b41038b053be528e535423e'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'HEROKU_POSTGRESQL_BROWN_URL'
GITHUB_USERNAME = 'gerbal'
CONTACT_EMAIL = ''
BLOG_TITLE = 'smartypants\' blog'
BLOG_TAGLINE = 'My pants are smarter than your\'s are'
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'DG7WDRJNDAYFWGFXTUA6PZM5V6MNLURDVPLOEWCWHUZBP7T45FCA===='
DISQUS_SHORTNAME = ''
USE_ADDTOANY = True
USE_SUBTOME = False
